import { FrameTemplate, TemplateStyleTheme } from '@/types/session';

export type ExportFormat = 'strip' | 'story' | 'feed';

export interface LayoutProfile {
  format: ExportFormat;
  canvasWidth: number;
  canvasHeight: number;
  headerY: number;
  footerY: number;
  getSlots: (w?: number, h?: number) => { index: number; x: number; y: number; width: number; height: number }[];
}

export const LAYOUT_PROFILES: Record<ExportFormat, LayoutProfile> = {
  // 1. Standard Vertical Photostrip (1080 x 3240, ~3.5 MP)
  strip: {
    format: 'strip',
    canvasWidth: 1080,
    canvasHeight: 3240,
    headerY: 90,
    footerY: 3120,
    getSlots: () => [
      { index: 0, x: 60, y: 180, width: 460, height: 620 },
      { index: 1, x: 560, y: 180, width: 460, height: 620 },
      { index: 2, x: 60, y: 840, width: 460, height: 620 },
      { index: 3, x: 560, y: 840, width: 460, height: 620 },
      { index: 4, x: 60, y: 1500, width: 460, height: 620 },
      { index: 5, x: 560, y: 1500, width: 460, height: 620 },
      { index: 6, x: 60, y: 2160, width: 460, height: 620 },
      { index: 7, x: 560, y: 2160, width: 460, height: 620 },
    ],
  },

  // 2. Story Format (1080 x 1920, ~2.07 MP)
  story: {
    format: 'story',
    canvasWidth: 1080,
    canvasHeight: 1920,
    headerY: 100,
    footerY: 1840,
    getSlots: () => [
      { index: 0, x: 70, y: 200, width: 450, height: 350 },
      { index: 1, x: 560, y: 200, width: 450, height: 350 },
      { index: 2, x: 70, y: 590, width: 450, height: 350 },
      { index: 3, x: 560, y: 590, width: 450, height: 350 },
      { index: 4, x: 70, y: 980, width: 450, height: 350 },
      { index: 5, x: 560, y: 980, width: 450, height: 350 },
      { index: 6, x: 70, y: 1370, width: 450, height: 350 },
      { index: 7, x: 560, y: 1370, width: 450, height: 350 },
    ],
  },

  // 3. Feed Portrait Format (1080 x 1350, ~1.46 MP)
  feed: {
    format: 'feed',
    canvasWidth: 1080,
    canvasHeight: 1350,
    headerY: 80,
    footerY: 1280,
    getSlots: () => [
      { index: 0, x: 80, y: 160, width: 440, height: 230 },
      { index: 1, x: 560, y: 160, width: 440, height: 230 },
      { index: 2, x: 80, y: 430, width: 440, height: 230 },
      { index: 3, x: 560, y: 430, width: 440, height: 230 },
      { index: 4, x: 80, y: 700, width: 440, height: 230 },
      { index: 5, x: 560, y: 700, width: 440, height: 230 },
      { index: 6, x: 80, y: 970, width: 440, height: 230 },
      { index: 7, x: 560, y: 970, width: 440, height: 230 },
    ],
  },
};

export const PHOTO_TEMPLATES: FrameTemplate[] = [
  // 1. PASANGAN & LDR (Romantis)
  {
    id: 'romantic_moment',
    name: 'Warm Romance',
    category: 'romantic',
    eventTag: 'Pasangan & LDR',
    badge: 'Populer',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#fff1f2',
    borderColor: '#fecdd3',
    borderWidth: 20,
    textColor: '#881337',
    subtextColor: '#9f1239',
    headerText: 'DUA TEMPAT • SATU MOMEN',
    footerText: 'selamanya dekat di hati',
    isPremium: false,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'midnight_velvet',
    name: 'Midnight Velvet Romance',
    category: 'romantic',
    eventTag: 'Anniversary Pasangan',
    badge: 'Eksklusif',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#2a0815',
    borderColor: '#d4af37',
    borderWidth: 22,
    textColor: '#fef3c7',
    subtextColor: '#e2b170',
    headerText: 'ANNIVERSARY ARCHIVE • DUA TEMPAT',
    footerText: 'dua hati • ribuan kilometer',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'sunset_terracotta',
    name: 'Warm Terracotta Sunset',
    category: 'romantic',
    eventTag: 'Kencan Berdua',
    badge: 'Eksklusif',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#fdf4ef',
    borderColor: '#e07a5f',
    borderWidth: 20,
    textColor: '#3d2621',
    subtextColor: '#6b4226',
    headerText: 'OUR GOLDEN HOUR • HARI KITA',
    footerText: 'kencan terindah dalam satu frame',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'vintage_polaroid',
    name: 'Vintage Polaroid Cream',
    category: 'romantic',
    eventTag: 'Pasangan & Kenangan',
    badge: 'Eksklusif',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#fef3c7',
    borderColor: '#fde68a',
    borderWidth: 24,
    textColor: '#451a03',
    subtextColor: '#78350f',
    headerText: 'SATU FRAME • POLAROID WARMTH',
    footerText: 'dua hati • satu momen',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },

  // 2. KELULUSAN & WISUDA (Graduation)
  {
    id: 'graduation_navy_gold',
    name: 'Alma Mater Navy & Gold',
    category: 'graduation',
    eventTag: 'Kelulusan & Wisuda',
    badge: 'Eksklusif',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#0a192f',
    borderColor: '#d4af37',
    borderWidth: 24,
    textColor: '#ffffff',
    subtextColor: '#ffd700',
    headerText: 'GRADUATION DAY • KELULUSAN KITA',
    footerText: 'Class of 2026 • Bersama Menuju Masa Depan',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'academic_emerald',
    name: 'Commencement Emerald',
    category: 'graduation',
    eventTag: 'Hari Wisuda',
    badge: 'Eksklusif',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#06281e',
    borderColor: '#c5d86d',
    borderWidth: 22,
    textColor: '#f0fdf4',
    subtextColor: '#86efac',
    headerText: 'COMMENCEMENT ARCHIVE • HARI WISUDA',
    footerText: 'toga terangkat • perjuangan terbayar',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },

  // 3. REUNI & SAHABAT (Reunion & Friendship)
  {
    id: 'reunion_retro_90s',
    name: 'Reuni Sahabat 90s',
    category: 'reunion',
    eventTag: 'Reuni Teman Lama',
    badge: 'Eksklusif',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#2a1b0e',
    borderColor: '#f59e0b',
    borderWidth: 22,
    textColor: '#fffbeb',
    subtextColor: '#fbbf24',
    headerText: 'REUNI SAHABAT • TAK PERNAH BERUBAH',
    footerText: 'cerita dulu, sekarang, dan selamanya',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'coffee_chill_club',
    name: 'Coffee & Chill Club',
    category: 'reunion',
    eventTag: 'Sahabat & Nongkrong',
    badge: 'Favorit',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#1c1917',
    borderColor: '#d7c4b7',
    borderWidth: 18,
    textColor: '#fafaf9',
    subtextColor: '#d6d3d1',
    headerText: 'KUMPUL BARENG • TEMPAT BIASA',
    footerText: 'secangkir kopi dan tawa tanpa akhir',
    isPremium: false,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },

  // 4. ULANG TAHUN & SELEBRASI (Birthday)
  {
    id: 'birthday_confetti_gold',
    name: 'Champagne Birthday Noir',
    category: 'birthday',
    eventTag: 'Ulang Tahun & Pesta',
    badge: 'Eksklusif',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#0f0f12',
    borderColor: '#f3d085',
    borderWidth: 22,
    textColor: '#ffffff',
    subtextColor: '#fde68a',
    headerText: 'HAPPY BIRTHDAY • HARI SPESIAL',
    footerText: 'tahun berganti • doa terbaik menyertai',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'birthday_pastel_blossom',
    name: 'Sweet Pastel Birthday',
    category: 'birthday',
    eventTag: 'Ulang Tahun Manis',
    badge: 'Populer',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#fdf2f8',
    borderColor: '#f472b6',
    borderWidth: 20,
    textColor: '#831843',
    subtextColor: '#9d174d',
    headerText: 'SWEET CELEBRATION • MOMEN MANIS',
    footerText: 'selamat bertambah usia dan bahagia',
    isPremium: false,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },

  // 5. KONSER & MUSIK (Concert & Festival)
  {
    id: 'retro_indie_cassette',
    name: 'Live Stage Indie Cassette',
    category: 'concert',
    eventTag: 'Konser & Festival Musik',
    badge: 'Eksklusif',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#181211',
    borderColor: '#ea580c',
    borderWidth: 22,
    textColor: '#ffedd5',
    subtextColor: '#fdba74',
    headerText: 'LIVE CONCERT VIBE • NADA BERSAMA',
    footerText: 'di bawah ritme dan panggung yang sama',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'cyber_y2k',
    name: 'Cyber Y2K Chrome',
    category: 'creative',
    eventTag: 'Indie & Y2K Future',
    badge: 'Eksklusif',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#090d16',
    borderColor: '#38bdf8',
    borderWidth: 20,
    textColor: '#f0f9ff',
    subtextColor: '#7dd3fc',
    headerText: 'SATU FRAME • FUTURE MEMORY',
    footerText: 'virtual sync • connected across city',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },

  // 6. VINTAGE, ANALOG & MINIMALIS
  {
    id: 'film_noir',
    name: 'Analog Film Noir 35mm',
    category: 'vintage',
    eventTag: 'Monokrom Sinematik',
    badge: 'Eksklusif',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#000000',
    borderColor: '#71717a',
    borderWidth: 22,
    textColor: '#fafafa',
    subtextColor: '#a1a1aa',
    headerText: 'SATU FRAME • 35MM MONOCHROME',
    footerText: 'cinematic intimate series',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'classic_strip',
    name: 'Classic Film Strip',
    category: 'classic',
    eventTag: 'Klasik Film 35mm',
    badge: 'Standar',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#18181b',
    borderColor: '#27272a',
    borderWidth: 24,
    textColor: '#f4f4f5',
    subtextColor: '#a1a1aa',
    headerText: 'SATU FRAME • MEMORIES',
    footerText: 'dua tempat • satu momen',
    isPremium: false,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'minimal_duo',
    name: 'Minimal Ivory Studio',
    category: 'minimal',
    eventTag: 'Minimalis Elegan',
    badge: 'Standar',
    description: 'Estetika studio monokrom bersih dengan palet warna stone ivory dan teks arang hangat.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#fafaf9',
    borderColor: '#e7e5e4',
    borderWidth: 16,
    textColor: '#1c1917',
    subtextColor: '#57534e',
    headerText: 'SATU FRAME ARCHIVE',
    footerText: 'simpel • tenang • abadi',
    isPremium: false,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  // --- KATEGORI KORAN & SURAT KABAR ---
  {
    id: 'the_daily_chronicle',
    name: 'The Daily Chronicle 1945',
    category: 'newspaper',
    eventTag: 'Koran Cetak Antik',
    badge: 'Eksklusif',
    description: 'Estetika surat kabar jadul tahun 1945 dengan tipografi mesin tik jurnalisme klasik.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#f4f0e6',
    borderColor: '#18181b',
    borderWidth: 14,
    textColor: '#111827',
    subtextColor: '#374151',
    headerText: 'THE DAILY CHRONICLE • EDISI KHUSUS',
    footerText: 'berita utama: dua insan dalam satu cerita',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'sunday_gazette',
    name: 'Sunday Morning Gazette',
    category: 'newspaper',
    eventTag: 'Koran Akhir Pekan',
    badge: 'Standar',
    description: 'Koran Minggu santai dengan kolom editorial bersih dan pembatas garis ganda tipis.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#fbf9f5',
    borderColor: '#d6d3d1',
    borderWidth: 12,
    textColor: '#1c1917',
    subtextColor: '#44403c',
    headerText: 'SUNDAY GAZETTE • WEEKEND EDITION',
    footerText: 'kabar santai • tawa ceria • akhir pekan',
    isPremium: false,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'tabloid_pop_press',
    name: 'Retro Pop Tabloid',
    category: 'newspaper',
    eventTag: 'Tabloid Pop 2000s',
    badge: 'Eksklusif',
    description: 'Nuansa tabloid hiburan era 2000-an dengan headline mencolok dan aksen kuning menyala.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#18181b',
    borderColor: '#eab308',
    borderWidth: 16,
    textColor: '#fef08a',
    subtextColor: '#fca5a5',
    headerText: 'HOT NEWS • EXCLUSIVE EXPOSE',
    footerText: 'pasangan terfavorit minggu ini terungkap',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'vintage_press_sepia',
    name: 'The 1920s Sepia Gazette',
    category: 'newspaper',
    eventTag: 'Koran Klasik 1920s',
    badge: 'Eksklusif',
    description: 'Kertas koran serat kayu masa lampau dengan tinta cetak timbal cokelat hangat.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#ebe3d5',
    borderColor: '#5c4033',
    borderWidth: 20,
    textColor: '#3e2723',
    subtextColor: '#5d4037',
    headerText: 'THE VINTAGE PRESS • NO. 1926',
    footerText: 'arsip kenangan cetak masa lampau',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  // --- KATEGORI MAJALAH & EDITORIAL ---
  {
    id: 'vogue_minimal_editorial',
    name: 'Vogue Haute Editorial',
    category: 'magazine',
    eventTag: 'Majalah Mode Haute',
    badge: 'Eksklusif',
    description: 'Tipografi majalah fashion kelas atas dengan kontras monokrom tajam dan tata letak elegan.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#09090b',
    borderColor: '#27272a',
    borderWidth: 16,
    textColor: '#f8fafc',
    subtextColor: '#a1a1aa',
    headerText: 'THE EDITORIAL ISSUE • VOL. 08',
    footerText: 'timeless elegance in every frame',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'harper_aesthetic_beige',
    name: 'Aesthetic Lookbook Harper',
    category: 'magazine',
    eventTag: 'Lookbook Musim Gugur',
    badge: 'Eksklusif',
    description: 'Estetika majalah gaya hidup Skandinavia dengan palet hangat oatmeal dan zaitun gelap.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#f7f2ea',
    borderColor: '#e7ded2',
    borderWidth: 14,
    textColor: '#1c2a24',
    subtextColor: '#4a554f',
    headerText: 'HARPER LOOKBOOK • AUTUMN ISSUE',
    footerText: 'paduan gaya dan senyum hangat kita',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'indie_zine_riot',
    name: 'Indie Underground Zine',
    category: 'magazine',
    eventTag: 'Zine Fotokopi Jalanan',
    badge: 'Eksklusif',
    description: 'Estetika zine fotokopi DIY musik bawah tanah dengan tekstur mentah dan garis tegas.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#27272a',
    borderColor: '#52525b',
    borderWidth: 18,
    textColor: '#f1f5f9',
    subtextColor: '#cbd5e1',
    headerText: 'ZINE COLLAGE • ISSUE #04',
    footerText: 'seni jalanan • kebebasan • suara kita',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'japan_citypop_magazine',
    name: 'Tokyo City Pop Magazine',
    category: 'magazine',
    eventTag: 'Majalah Pop Jepang 80s',
    badge: 'Eksklusif',
    description: 'Gaya sampul majalah musik pop Jepang era 1980-an berpadu warna neon pastel yang semarak.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#0f172a',
    borderColor: '#fda4af',
    borderWidth: 16,
    textColor: '#fecdd3',
    subtextColor: '#7dd3fc',
    headerText: 'CITY POP SPECIAL • MIDNIGHT TOKYO',
    footerText: 'alunan melodi malam di tengah kota',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'kinfolk_slow_living',
    name: 'Kinfolk Minimal Living',
    category: 'magazine',
    eventTag: 'Majalah Slow Living',
    badge: 'Standar',
    description: 'Desain majalah arsitektur dan slow living yang tenang, lapang, dan bernyawa.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#fcfaf6',
    borderColor: '#e5e0d8',
    borderWidth: 12,
    textColor: '#292524',
    subtextColor: '#57534e',
    headerText: 'SLOW LIVING • THE SIMPLE MOMENT',
    footerText: 'menikmati detik berharga tanpa tergesa',
    isPremium: false,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  // --- KATEGORI PERNIKAHAN & PERTUNANGAN ---
  {
    id: 'wedding_ivory_botanical',
    name: 'Botanical Garden Wedding',
    category: 'wedding',
    eventTag: 'Pernikahan Botani Emas',
    badge: 'Eksklusif',
    description: 'Sentuhan anggun daun eukaliptus botani dan sutra gading untuk mengabadikan janji pernikahan.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#fcf9f2',
    borderColor: '#15803d',
    borderWidth: 14,
    textColor: '#14532d',
    subtextColor: '#854d0e',
    headerText: 'THE VOWS • FOREVER & ALWAYS',
    footerText: 'janji suci terpatri dalam cinta abadi',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'engagement_blush_lace',
    name: 'Blush Ribbon Engagement',
    category: 'wedding',
    eventTag: 'Lamaran & Pertunangan',
    badge: 'Eksklusif',
    description: 'Nuansa manis bunga mawar dan pita blush lembut untuk merayakan momen lamaran bahagia.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#fff1f2',
    borderColor: '#f43f5e',
    borderWidth: 16,
    textColor: '#881337',
    subtextColor: '#9f1239',
    headerText: 'SHE SAID YES • SATU LANGKAH MENUJU DEPAN',
    footerText: 'cincin terpasang • dua hati bertaut',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'royal_golden_nuptial',
    name: 'Royal Golden Nuptial',
    category: 'wedding',
    eventTag: 'Resepsi Pernikahan Mewah',
    badge: 'Eksklusif',
    description: 'Kemewahan beludru marun kerajaan berpadu aksen emas sampanye untuk resepsi istimewa.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#3a080c',
    borderColor: '#eab308',
    borderWidth: 22,
    textColor: '#fef08a',
    subtextColor: '#fed7aa',
    headerText: 'THE ROYAL WEDDING CELEBRATION',
    footerText: 'kebahagiaan megah bersama keluarga tercinta',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  // --- KATEGORI WISATA & PERJALANAN ---
  {
    id: 'travel_post_postcard',
    name: 'Vintage Airmail Postcard',
    category: 'travel',
    eventTag: 'Kartu Pos Wisata Jadul',
    badge: 'Eksklusif',
    description: 'Replika kartu pos udara antik lengkap dengan aksen garis khas pos dan stempel pengiriman.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#fefae0',
    borderColor: '#b91c1c',
    borderWidth: 16,
    textColor: '#1e3a8a',
    subtextColor: '#991b1b',
    headerText: 'PAR AVION • WANDERLUST POSTCARD',
    footerText: 'terkirim penuh rindu dari seberang pulau',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'bali_tropical_breeze',
    name: 'Tropical Sunset Coast',
    category: 'travel',
    eventTag: 'Liburan Pantai & Senja',
    badge: 'Standar',
    description: 'Semilir angin pantai tropis dan warna pasir senja untuk mengenang liburan bersama.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#fff7ed',
    borderColor: '#fb923c',
    borderWidth: 14,
    textColor: '#064e3b',
    subtextColor: '#9a3412',
    headerText: 'SUNSET BY THE SHORE • BALI ESCAPE',
    footerText: 'deburan ombak • tawa lepas • matahari terbenam',
    isPremium: false,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'japan_train_ticket',
    name: 'Shinkansen Rail Ticket',
    category: 'travel',
    eventTag: 'Tiket Perjalanan Kereta',
    badge: 'Eksklusif',
    description: 'Desain tiket kereta cepat Jepang bernuansa retro untuk pelancong dan petualang.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#f0fdf4',
    borderColor: '#166534',
    borderWidth: 16,
    textColor: '#14532d',
    subtextColor: '#15803d',
    headerText: 'SPECIAL EXPRESS TICKET • CAR 04',
    footerText: 'melaju cepat menembus panorama pemandangan',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'mountain_mist_forest',
    name: 'Highland Mist Forest',
    category: 'travel',
    eventTag: 'Piknik & Hiking Pegunungan',
    badge: 'Standar',
    description: 'Sejuknya kabut pagi dan aroma pinus pegunungan untuk kenangan pendakian bersama sahabat.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#f1f5f9',
    borderColor: '#475569',
    borderWidth: 14,
    textColor: '#0f172a',
    subtextColor: '#334155',
    headerText: 'HIGHLAND MEMORIES • PINE CANOPY',
    footerText: 'udara dingin gunung • pelukan hangat',
    isPremium: false,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  // --- KATEGORI KOMIK, MANGA & POP ART ---
  {
    id: 'shonen_manga_halftone',
    name: 'Shonen Manga Screentone',
    category: 'comic',
    eventTag: 'Komik Manga Jepang',
    badge: 'Eksklusif',
    description: 'Estetika lembaran manga Shonen Jepang dengan border panel tegas dan tipografi aksi onomatope.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#f8fafc',
    borderColor: '#020617',
    borderWidth: 24,
    textColor: '#09090b',
    subtextColor: '#475569',
    headerText: 'CHAPTER 01 • OUR STORY BEGINS!',
    footerText: 'bersambung ke halaman berikutnya...',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'pop_art_roy',
    name: 'Retro Pop Art Comic',
    category: 'comic',
    eventTag: 'Pop Art Klasik 60s',
    badge: 'Eksklusif',
    description: 'Warna primer tegas dan outline tebal gaya komik Pop Art 1960-an karya Roy Lichtenstein.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#fef08a',
    borderColor: '#000000',
    borderWidth: 22,
    textColor: '#b91c1c',
    subtextColor: '#000000',
    headerText: 'POW! AMAZING MOMENTS IN COLOR',
    footerText: 'warna ceria • ledakan tawa bersama',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  // --- KATEGORI K-POP & IDOL FANDOM ---
  {
    id: 'kpop_holographic_pc',
    name: 'Holographic Idol Photocard',
    category: 'fandom',
    eventTag: 'Kpop Idol Photocard',
    badge: 'Eksklusif',
    description: 'Nuansa photocard idol K-Pop dengan aksen kilau pastel iris dan frame melengkung presisi.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#fdf4ff',
    borderColor: '#c084fc',
    borderWidth: 18,
    textColor: '#6b21a8',
    subtextColor: '#9333ea',
    headerText: 'OFFICIAL PHOTOCARD • SPECIAL DROP',
    footerText: 'koleksi cinta untuk bias tersayang',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'lightstick_concert_night',
    name: 'Ocean of Lightsticks',
    category: 'fandom',
    eventTag: 'Malam Konser Fandom',
    badge: 'Eksklusif',
    description: 'Gemerlap lautan cahaya lightstick di dalam stadion malam hari yang penuh kehangatan emosional.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#180d2b',
    borderColor: '#7c3aed',
    borderWidth: 16,
    textColor: '#e9d5ff',
    subtextColor: '#c4b5fd',
    headerText: 'STADIUM TOUR • OCEAN OF LIGHTS',
    footerText: 'nyanyian serentak ribuan suara di bawah panggung',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  // --- KATEGORI RETRO & NOSTALGIA ---
  {
    id: 'super8_film_warm',
    name: 'Super 8mm Kodachrome',
    category: 'vintage',
    eventTag: 'Seluloid Film Super 8',
    badge: 'Eksklusif',
    description: 'Rona warna emas hangat khas seluloid rol film Super 8mm era 1970-an yang tak lekang waktu.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#fef3c7',
    borderColor: '#b45309',
    borderWidth: 18,
    textColor: '#78350f',
    subtextColor: '#92400e',
    headerText: 'KODACHROME 1974 • REEL NO. 3',
    footerText: 'cahaya hangat mentari masa lalu',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'gameboy_pixel_8bit',
    name: '8-Bit Retro Arcade',
    category: 'vintage',
    eventTag: 'Konsol Gameboy Nostalgia',
    badge: 'Eksklusif',
    description: 'Kenangan masa kecil bermain konsol handheld 8-bit dengan warna layar LCD monokrom hijau ikonik.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#e2e8f0',
    borderColor: '#334155',
    borderWidth: 22,
    textColor: '#14532d',
    subtextColor: '#1e293b',
    headerText: 'PRESS START • PLAYER 1 & PLAYER 2',
    footerText: 'level tamat • persahabatan tanpa akhir',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'vhs_glitch_retro',
    name: 'VHS Tape Rewind 1988',
    category: 'vintage',
    eventTag: 'Kaset Pita VHS 1988',
    badge: 'Eksklusif',
    description: 'Sentuhan garis pelacak kaset video VHS era akhir 80-an dengan paduan warna neon elektrik.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#090d16',
    borderColor: '#f472b6',
    borderWidth: 16,
    textColor: '#2dd4bf',
    subtextColor: '#f472b6',
    headerText: 'PLAY >> 00:24:1988 • HI-FI STEREO',
    footerText: 'putar kembali setiap detik berharga',
    isPremium: true,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  // --- KATEGORI MINIMALIS SKANDINAVIA & GALERI SENI ---
  {
    id: 'nordic_sand_studio',
    name: 'Nordic Dune Studio',
    category: 'minimal',
    eventTag: 'Desain Skandinavia Alami',
    badge: 'Standar',
    description: 'Ketenangan desain interior Skandinavia bergaris bersih dan palet warna bumi netral.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#f5f5f4',
    borderColor: '#d6d3d1',
    borderWidth: 12,
    textColor: '#1c1917',
    subtextColor: '#44403c',
    headerText: 'NORDIC ARCHIVE • MINIMALIST FORM',
    footerText: 'ruang tenang • kejernihan rasa',
    isPremium: false,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
  {
    id: 'pure_monochrome_gallery',
    name: 'Art Gallery Exhibition',
    category: 'minimal',
    eventTag: 'Pameran Galeri Seni Modern',
    badge: 'Standar',
    description: 'Kemurnian dinding museum seni modern dengan pigura hitam tipis dan fokus total pada subjek foto.',
    version: 1,
    aspectRatio: '1:3',
    canvasWidth: 1080,
    canvasHeight: 3240,
    backgroundColor: '#ffffff',
    borderColor: '#09090b',
    borderWidth: 16,
    textColor: '#09090b',
    subtextColor: '#52525b',
    headerText: 'EXHIBITION ARCHIVE • INSTALLATION 01',
    footerText: 'karya seni nyata dari momen keseharian',
    isPremium: false,
    slots: LAYOUT_PROFILES.strip.getSlots().map((s) => ({
      ...s,
      aspectRatio: 4 / 3,
      participantRole: s.index % 2 === 0 ? 'creator' : 'partner',
    })),
  },
];

export function getTemplateById(id: string): FrameTemplate {
  return PHOTO_TEMPLATES.find((t) => t.id === id) || PHOTO_TEMPLATES[0];
}

export function getStyleTheme(template: FrameTemplate): TemplateStyleTheme {
  if (template.styleTheme) return template.styleTheme;
  if (template.category === 'newspaper') return 'newspaper';
  if (template.category === 'magazine') return 'magazine';
  if (template.category === 'wedding') return 'wedding_botanical';
  if (template.category === 'travel') return 'postcard_airmail';
  if (template.category === 'comic') return 'comic_screentone';
  if (template.category === 'fandom') return 'kpop_photocard';
  if (
    template.id.includes('film') ||
    template.id.includes('noir') ||
    template.id.includes('retro') ||
    template.id.includes('cassette') ||
    template.category === 'vintage' ||
    template.category === 'classic'
  ) {
    if (template.id === 'gameboy_pixel_8bit') return 'retro_arcade';
    return 'film_35mm';
  }
  return 'minimal_clean';
}
